services:
  - type: web
    name: Twitter-clone-neex
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan optimize
    startCommand: php artisan serve --host=0.0.0.0 --port=${PORT}
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
